<?php
$jokes = array("Now I have iOS 7.1 can I downgrade to 7.0.4 with the use of my SHSH blobs of iOS 6.1.2? Why?",
"I use are only used for legitimate medical bigboos piracy",
"I'd like to shove my ipod in iH8sn0ws face and say \"you put dat cydia on my ipod you sickk guy\"",
"found my old iphone 3gs, and accidentally update it to ios 6.1.6",
"I would go in the dschungel",
"hi i have a 3gs new bootrom which i accidentally updated with itunes to 6.1.3, ",
"Rio djanrero is is a bigg city",
"The island is an Ort, who were anywere but I don't know were",
"The poeple in tokio speek japasese",
"In dis capital is often sunny and well weahter",
"And maybe I drive sometimes to jamaica",
"i her much that the city cool is",
"My father lerns italien",
"I like so much france",
"I travel wit my family",
"I love if the sonne shine",
"You can fetch on the beach",
"In the forest are many wild anymalls",
"If I could I'll explore to Antactic",
"I want to go to amerike becaus my family was ther born.",
"There lived indianer who catched their food without revolver",
"breakfast = In the mornin you eat someone",
"-------------------------PIRACY------------------------ WHO GIVES A (S H I T) ABOUT PIRACY DONT WASTE YOUR MONEY ON SOMETHING THAT IS VIRTUAL WHEN YOU CAN GET IT FOR FREE AND PLUS PIRATING CYDIA APPS AND TWEAK ISN'T ILLEGAL SO GO AHEAD AND GET PAID APP AND TWEAKS FOR FREE WHO GIVES (TWO FLYIN S H I T S ABOUT PIRACY)CAUSE I DONT I NEVER BOUGHT A CYDIA APP OR TWEAK EVER SINCE THE IOS 6 JAILBREAK I'VE ALWAY GOT PAID TWEAKS FOR FREE THERE IS NO SENSE IN BUYING THEM WHEN U CAN GET THEM FOR FREE///////////JUST SAYING",
"Wen an jailbroken device stucks on bootloop then wat we can do fix it?",
"my ipod5g doesnt want to turn on it worked great till rait know i install a tweak called messages+ the free trial then it respring went in safe mode i went to cydia it got blacked i erased from history and opened again and it stay stucked so i turned it off and it doesnt want to turn on anymoreeeeeeeee and i connected to itunes and it does detected it please help any fix???????",
"Has anyone really been far even as decided to use even go want to do look more like?",
"You've got to be kidding me. I've been further even more decided to use each go need to do look more as anyone can. Can you really he far even as decided half as much to use go wish for that? My guess is that when one really been far even as decided once to rise even go want, it is then that he has really been far even as decided to use even go want to do look more like. It's just common sense.",
"well why did it take everything off my iphone but the apps have downloaded from the app store",
"Guys i am stupid i admit, This is the point of situation, i got a iphone 5s and after jailbreak i was getting some errors and i fought it was from cydia and evasi0n, so i deleted them, i know, what a f** stupid i am, now when i re-try to re-jailbreak of course evasi0n says i cant and even when i try doesnt work. As you imagine i cannot restore or loose 7.0.4 plus will be forces to install 7.1. I did not install openssh when i was with cydia no. Do i have any other chance? Thanks for all welcome helps in advance.",
"where the fields are actually prisons, and the flowers are actually jail cells",
"Have you tried turning it off and on again?",
"i want to extend my memory on iphone 4 to 32gb, is it possible throuch jailbreak and a virtual mashine",
"No I mean its very small and I can't do anything with it",
"What do you mean by Home? Is that the button on the Mac keyboard in the middle of the fn, page up, page down, delete, end, section?",
"I have notice since I have upgraded to 7.06 and added new jailbroken evasion 7-1.0.6, I have noticed that extension consistently when loaded causes a safe mode reboot is cydia substrate with mobile substrate. I do not believe this is compatible with the system. If you remove them you surely reboot the application without the safe mode and have limited jailbroken capabilities. But only extension I have found since i have upgraded again last month is cydia substrate with its mobile substrate. Be ware that you cannot jailbreak as long as this is not fixed which has not been fixed",
"I know there is cydia in iOS3.1.3 and it works flawlessly, but when whited00r team create Whited00r 7 with white theme.... some of cydia app text cannot be read easily.... so can you make cydia app version for Whited00r 7? I mean can you make cydia app theme fits Whited00r seven theme.... the text is white in white background so can you make the text black? because whited00r theme cannot change it because they dont know the source code of cydia..... Please make cydia fits whited00r 7..... iPhone 2G and 3G. and iPod touch 1G and 2G users, with Whited00r 7 installed are also many, so please dont ignore our request.... thank you! :D",
"Hello i have ipode tuch 4g ios6.1.5 and jailbreak by redsnOw 0.9.15b3 The problem is that reboot all the time and Cydia crashed --- many diagnostics....!!!!1",
"How to buy chips free on teen patti indian poker by octro ?",
"My friend told me to download this, I did. He didn't tell me what it does or what it's for or anything? But he did mention that I can download all apps and music for free, is it true that I can?",
"I downloaded it from site in the internet. It have been worked before but i had to delete it . Now after trying reinstall it, All my memory disappear",
"I don't know what tweaks are. I did what it told me to do, I clicked on the app, then it started rebooting.",
"Does anyone know how much weigh jailbreak is?",
"my system wont confugure when i first am jailbreaking?",
"Heeeellllpppp when I went to get rid of something cydia disappeared plz send this by email I'm more likely to read it then plz help I need it sooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooobad :) thanks bye",
"weather-problem-i-recently-jailbreak-to-704-iph5-i-remove-cities-from-weather-app-but-it-comes-again-auto-please-help",
"i had my i pod touch jail broken but i removed the jailbreak for some reason",
"Camera, Facebook and Twitter apps are crashing. Please post the solution.",
"First off, I don't pay for any of the ones that BigBoss & others wants me to pay for, I get them from other repos\" http://bit.ly/1aFZ3pl", "Please help theres this calculator icon that shows up between my timer and camera icon on my Jailbroken iPad 4 running ios 7.",
"yeh i know sorry and it aint play ground when they are saying i threatened to stab someone haha and that i take drugs when i never will ever never even drank before and everyone i know has in my school. can you please help me though i really want to jailbreak my ipad as i am on it more than my phone",
"so I was on cydia, then I tried to get the beta repo for bite SMS but it wouldn't work so I decided to respring and now and a bunch of icons are in the home screen like set up Siri and other stuff and when I click them they are blank but like they won't go a way and I tried deleting some folders in ifile and now my phone goes into safe mode when I use the control center and cydia and the AppStore , the settings app is like gone and I tried deleting the cydia installer and some other things to fix things but it just made things worse and I don't know what to do my phone keeps crashing into safe mode and I keep deleting stuff in ifile but nothing is working ,",
"I don't know what caused it, I looked at the help button for safe mode and it still seems to solve absolutely nothing. I don't know what caused it.",
"Hello 5s ios7, just jail broke. Safari and chrome and fb all crash immediately on opening. I do not have any of that pirated stuff (appsync or whatever is in the jailbreakqa) any suggestions? Tried reinstalling gzip and uikit as suggested in a Jews thread",
"Battery harmful after jailbreak",
"Im new to jailbreak lol i just jailbroke my phone and how do i get instagram followers on cydia and in this one video i watched this guy was on instafollow and he was buying coins to get followers but he didnt pay cuz he had a jailbroken phone",
"What is the winterboard used for? What is the winterboard? What are the themes of winterboard? I have it and I have no clue what to do with it or wt is it",
"I don't know why but none of my stock or wallpapers that were downloaded into my wallpaper folder ard gone. My dynamic wallpapers are their but their nothing in my stock wallpaper folder.",
"I when here: http://gs.apple.com download open run as adm plug the iphone the bottom jailbreak is off",
"iPhone 5s 7.0.4 restrings when opening camera and safari",
"I tried these steps all day and nothing, I will tell u what's wrong, last night cydia crashed and my phone has been fd up every since and look at all the comments in this forum it is not a quinceadence!!",
"Hey i jailbreaked my ipad mini 1 before new year when it came out and i installed a tweak that would add repo's with ios 7 tweaks wich screwed my cydia cause then the fix of deleting things in my list folder but those repo's where still there then tried to delete that tweak wich gone wrong and those repo's where still there then deleted my partial folder readded it but still got the same problem then deleted my metdata.plist wich kinda fixed it cause now it ask me what type of user iam then i choose user press done and then it crashes after anwhile i managed to install mobile terminal with ifile wich screwed up my safari app then i tried a fix for that wich screwed up safari and the mail app",
"I don't know what happened but now when I try to known the camera app it crushes. Any solutions for this?",
"After many attempts to restore in itunes, getting the 3194 error, trying to fix the 3194 error, messing with ireb, ifaith, ieverything, I am to the point of using my glock 36 on it.",
"helloo!! ive got problem for my dailpad when i try to controll how mutch money ive got o. my phone with a star like this (). when i try to call like this ()123# a star getting smaller.. i need bigger star to fix my dailpad",
"There is nothing inside in my package",
"If i restore cydia it will diseppear? Hop sow to do it again clear!",
"Error 3119 in DFU reparing !!! plase help i nedd this iphone start!!",
"plenty planetary party pirates pilfering poor pricks pension pots provoking prudence",
"How do I keep my iPhone 4s jailbreak stuck on the evad3rs apple?",
"Where ia da agagaffufj. Ok well if it's not illegal how about I use a cydia app to bake potatoes?",
"Plus even Spire can't go on a iPad and is total crap, ok hothead? Don't get all pissed on me because anytime I want I can email my dad to let me borrow his 4-inch army knife....",
"How do i uninstall springboard?",
"my car ran out of gas because i havent made a sandwich in ten years",
"Cant find cydia i think i might have deleted it",
"What does no action mean?",
"Ok i found a Iphone 4 in my couch screen was black would not boot up I replaced every flex cable as well as the digitizer and LCD thinking maybe it was a hardware problem still nothing so I tried restoring and got a error message so I put phone in Dfu mode tried restoring and error 1601 phone still black screen I then tried jailbreaking with red snow and it always stops at the waiting to reboot I then tried restore via iTunes again same error message",
"just master quested the water temple without the Zora tunic",
"What do you mean mac address?",
"Why come ModMyi messed up my phone when I downloaded it I want to get Zepplin but it said something about bigboss? I have Redsnow btw",
"Juan and Consuela went to the pizza place. He had his piece and she got herpes",
"He is the stupid dude who was in the store and now nobody knows him anymore", "Disk full", "I want to confirm that, your post is so interesting. It contains a lot of important and useful information. I got a lot of great things. Thank you so much!",
"It suck you I don't much apple but windows I can show what windows really do.",
"goodnight to all anf the jailbreak is ready call me ok?",
"after upgrade to ipod baseband ,install cydia. downgrade is failed why? give me a solution",
"I have been jailbroke on my ipod touch 3rd generation ios 5.1.1 absinthe or green poison jailbreak for a couple weeks now and decided to get touchposé+ so it worked for the rest of that day so ok and then I shut it off for the night you now and then when I tried turning on in the morning at first I eont wouldn't let me touch the screen like I was touching thw screen but nothing was happening so then when I decided to wait a little bit rhen It rebooted out of nowhere and kept kept rebooting and then finally it went into safe mode but then I was able to push the key but right after I got almost done tpying in the first 2 numbers in my passcode it resprang and it kept respringing after 2 second of having booted and it did that till it died PLEASE HELP ME!!!!!!!!! and I apologie for the story it just I didn't want to leave anything else out thanks",
"Where can I get cydia plz tell me and when the new cydia coming out kik me or email me plz I won't tell I give my word I won't tell My email is josuedelrio20@gmail.com Kik:mercyallow",
"It had the spinning white circle in the middle of the screen and so i just waited for three days.",
"is ifaith an ios app??",
"Hi if i have jailbroken iphone5 and i have downloade apps from repos can i back up my cracked apps after downloading ios 7???",
"was googling incase anyone had shsh blobs to dl?",
"Ok i uninstalled the mobile substrate..But almost all tweaks that i want to install, need mobile substrate.. Is there any alternative tweak for mobile substrate?",
"how could i know if my iphone career is locked??",
"firmware 04.12.01 iphon 4 is unclockable? please tell me the way to jailbreak",
"I've bought an iphone to a a guy. It looked just like iOS. After trying to do a reset, it works as an android!!! Can I restore iOS? How? Thanks",
"Xcuse me but I have my bachlers degree in criminal background stuff and I am a police officer so u best stop writing this phone now..or ill send u a bug good bye now..",
"Last tools jailbreak is disable auto update from apple ? Because children on my family. Is play. My. Device and press more anything Plz. Answer. Me Thank. You",
"pls help me out in a gr8 confusion i hv iphone 4 n it was jalbroken n now my lock key is nt working n nw i want to get it replaced bt istore as it is in warranty (purchase march 2013).",
"but the soft of unthreaded jb it no work",
"When in sleep or lock me I still no service or reach my Iphone 4 (6.0.1) word t now really tired of it! search on google and various forums for days and no solution found if I release him he will instantly search and I'm right as long as I reach him, but do not lock, there is nothing wrong",
"SO THIS MORNING MY IPHONE 3GS SUDDENTLY SHUT OFF AND TUREND BACK ON BUT WOULDNT GET PASS THE APPLE LOGO SO I TREID TO RESTORE VIA ITUNES AND DIDNT WORK TRIED 6 TIMES BEFORE IT WORKED BUT IT GOT UNACTIVATED SINCE I ACTIVTED DURING JAILBREAK. THEN I TRIED TO JAILBREAK AND ACTIVCTE AGAIN BUT MY POWER BUTTON DOESNT WORK SO I USED TINY UMBRELLA TO ENTER RECOVERY MODE AND THEN I USED REDSNOW'S ENTERING DFU IPSW THING SO I DID THAT THEN WENT TO ITUNES AND CLICKED SHIFT+RESORE CLICK THE FILE AND IT ENTERED DFU MODE THEN I OPENED REDSNOW AND IT DID SOMETHING BEFORE IT WAS FINISHED IT CRASHED AND THEN I OPEND REDSNOW AGAIN AND IT SAID IPHONE WAS IN SOFT DFU MODE THEN I TRIED TINY UMBRELLA TO EXIT RECOVERY MODE BUT DIDNT WORK THEN I TRIED TO RESTORE TO THAT DFU IPSW THING AND IT WENT ALL THE WAY TO PREPARING IPHONE FOR RESTORE THAT DIDNT WORK THE I TRIED THE SAME THING BUT OPENED ITUNES AGAIN AND TRIED TO PLAIN RESTORE AND SAME THING HAPPENED IPHONE 3GS SCREEN IS STILL BLACK I TRIED EVERYTHING I KNOW PLZ HELP IM ON IOS 6.1.3 IPHONE 3GS.",
"Sometimes if you cant get the redsnow to recognize the device in dfu mode or pwndfu mode that you set up, then make sure you get redsnow to set up the pwned dfu, then disconnect your device and place into the freezer for about 5-8 mins -(use at own risk and this is to fully power of the device-works too-verified.)",
"i have iphone 4s iso6.1.2 yesterday i install one app from cydia i dont know what heppen cydia notification come out \"CLEAR UNSAFE IGNORE RECOMENDED\" i click on CLEAR after that my phone restat and my cydia app and which install throuh cydia not working apps open and close please frndz help me to fix this",
"I own iPhone 3G Update worked for the network and lock the system did not hold to open",
"I have a serious problem i have a iphone 5 running on 6.1.2 its jailbroke i used a app in cydia called iLEX R.A.T I picked number 12 in mobileterminal which is revive,speed up,clean up after the iphone rebooted it got stuck in DFU MODE I finially got it to come on after two days of using recboot and tinyumbrella when it open up i had no icons on my phone not even the phone icon nothing on my phone but one app i bought from the app store i dont have the messege app are the itunes store app i have nothing not even the setting app i cant text are make phone calls i can answer the phone when someone calls and my siri still works i tried to get siri to open up the setting it says there no app on my phone called setting i tried to get it to call some of my contacts it recognizes there names but when i try to call i get some kind of url error ive tried to restore my phone from a old backups but when it finishes it opens up the same way with no icons ive tried SemiRestore and all i get is a error saying assertion failed program file device manager,cpp expression afc_file_ref_open(connection,path,1,&fileRef)==0.",
"with iphone in that DUI mode or w/e it is",
"my iphone is 3g ios 4.1. i update my iPhone by iTunes. now my iphone is not work. why???? what i do ?",
"why here said me no?",
"you telling me a lier?",
"Is the \"Unja1l\" Jailbreak fake?",
"Why does downloads on cydia always depend on things? How do I fix it? All packages depend on libhide and preferenceloader normally. HELP ME!",
"Hi I need help on how to restore my iPhone 4 without a computer because I don't have access to one and my phone was jail broken and I erased cydia my version: 6.1.2 (10B146) , Model: MC608LL/A , Modem Firmware: 04.12.05",
"did you say you even have the donkey?",
"is abhshinthe real or fake",
"can you mms yourself",
"Does it erase jailbreak",
"So I have upgraded to iOS 6.1.3 (don't know why but just did)",
"if i make a ssh-conection to my iDevice (iPad 3 or iPhone 3gs) there is an delay the keystrokes aren´t shown emidetly as on my pcs. Do You have any ideas? oh if i make an download or i´m surfing simuntainusly it´s better.",
"My ipod is 5g and with the update iOS 6.1.3 people say you can jail break it but it saids on 1 website that my ipod is to new but on the app it says the my device is not supported could you PLEASE make it so I and many people can use jail break",
"sir this need a my pc but no free download any site plz help i wont this file gave download link this problem how to solve plz plz help send mail kumarbharat758@gmail.com twitter @bk_mba prehacked dotnetfx45_full_setup.exe",
"is anyone using ios 7 beta? i want to try it but i want to know that will be there any problem of beta version? has anyone encountered any problem yet with ios 7 beta version yet?",
"i am having iphone 3gs with new boot room, having ios 4.2.1 jailbroken and unlocked piece , having installed cydia, and also having ultrasn0w, i want to upgrade atleast ios to 5 or more, please help please send on tushki943@rediffmail.com, thanks in advanced!!!!",
"whem i am using snowbreeze i got and error snow breeze failed to crete firmware",
"Need help to solve a problem by myself",
"So all I want to know is there any diffents in black rain, red sown,evasion, and green posing the resin I want to know this is beacause I may have to rejailbreak my device with one of these jailbreaking sources I know.",
"People from my church take my iphone and change the password (I normally don't have a password) what tool/tween should I use to get back at them or just simply get in my iphone",
"I have a iPad 2 6.1.3 can I get it tethered?",
"I lost firmware which I use to just boot my iPhone 4S every time Plz tell me how I can get back correct version of firmware for just boot my iPhone Plz reply as soon as possible Thanks in advance!",
"I live in Bosnia and even the Maps app cant find any roads,how the hell is Photos gonna organise my photos.And I take game screenshots.",
"Is Safari still using Google,and can you still use it to watch porn?",
"please respond me",
"So now this iPhone become a garbage.",
"I need the phone by tomorrow and it's been like this for like 2 months now.",
"I got cydia and downloaded a package in which I was displeased with.",
"Is it possible for me to get back Cydia?",
"iPad 4 is stuck on apple logo after deleting cydia.",
"My cousin removed cydia installer from my iphone 5 ios 6.1.2.",
"hi I downloaded this and now my ipod wont turn on can you please help me I don't know what to do",
"I was trying out themes, and I deleted one i did not like and cydia disappeared after the re-spring.",
"My understanding, 0.9.15b3 is for A4,right? which is the latest version for for 4S A5?....and what is the step in detail?",
"I've an iPhone 4 which stucked in soft dfu mode.",
"I've really tried every solution, what can be found here and on the net, so please do not close this topic, until we have real solution!",
"Please also not post links to how to enter DFU mode, I know the process, but for this situation its not working!",
"iPhone 4 hardly stucked in SOFT DFU mode",
"I went into the Cydia app and deleted the Cydia Installer, thinking it would maybe undo the jailbreak. This was a bad idea, and now I have a jailbroken Ipod with no Cydia app.",
"i think ive deleted siri off from ifile and is there way to restore it?",
"Work with your partner to find the right balance of power and grace in your collective learning.",
"The Cydia features forward and backward motion by both partners that are coordinated with complex footwork.",
"Partners should apply firm pressure against one another, but should avoid overpowering the other person.",
" do you know any website thats provide a relock service for iphone <+justinred> you want to lock an unlocked phone? yes i got scammed and wanna lock it",
" whenever this damn stream starts working again:[ all i can hear is audio",
"i'll be back to answer in 10 mins after i have a smoke since you are impatient",
"will you help me?",
"another option please",
"i don't want to how to open it",
"so what part of two options wasnt understandable?",
"how i know if battery dies?",
"cant do step 2 till youve done step 1",
"guess someone was there that didn't like it",
"I want to be server op :(",
"ok it now sais missing keys.plist data for this build",
"Using Unlocked Verizon iPhone 5 with Rogers and Verizon simultaneously",
"Are the ipad's shsh blobs compatible with apple tv?",
"I bought iphone 3gs jailbroken with ios 4.1 and I reset everything on it meaning it will erase everthing on the phone so I did this and my phone came up to a stuck silver apple so I read a forum and told me to plug my iphone to the computer using itunes to restore it and never knew u shouldnt upgrade a jailbroken iphone with itunes to ios 6 and I did so after my upgrade to ios 6 my phone came up and I was glad to see my phone rise up again but after the software finished loading on my phone it told me searching and later told me no service so I should try connecting to itunes to set it up but still nothing has been done to get network any help to my problem please I need a solution please",
"tried to jailbreak my iphone4 ios6.1.3 with tetherd way on redsnow but it always fail after press on 3 bottoms it load first stage and second stage they it says reboot and when it trys to reboot message appears says ''exploit failed'' tried to run as admin and i disposable my antivirus(kis) and many other actions ! but all failed and i tried the solutions for same problem but it all fail like me so plzzz give me a good action dont want to hear some stupid fail solutions....Thx",
"1st. my jailbreak damaged and it's not work anymore and i will update my ios 6.0.1 to ios 6.1 and am asking if that new update makes me lose my apps or it will keep everything as it is ??",
"tried for many times to backup my jailbroken apps on my iphone to itunes but it doesn't work i tried several sources to appsync but it always failed and i tried to update and sync my free apps over itunes and doesn't get updated can i have help?",
"hi again ... after shutdown hackolus appsync becomes not working but i found out another new source to download cracked apps but the problem is i cant transfer these apps to my itunes or my pc i asked many people but i found no answer so can any one help?",
"hi i want to know how can i change udid for apps such as hotspot..atc do cydia have app for change the udid?",
"i just updated my ios 6.0.1 to ios 6.1 but someone told me i will never nothing of my apps and everything will work fine without losing any app and that's not true i lost everything every cracked app every folder and every thing now can anyone help me ? coz i did backup this device before do update so i need help !",
"I asked my self what is the best in jailbreak and i didn't find answer for me it was for paid apps but what's the best thing in it y people make jailbreak if it's not for hacking games or take paid ones for free so what do i have to do with cydia or jailbreak ???",
"for some reasons i lose karma and i win karma but i dont know what can i do with it and if my karma become 0 do the website will ban me ? or i will can't ask more questions here or what will happen??",
"hi after jailbreak my iphone on ios 6.1 i cant transfer any paid or free app to my itunes i tried many times but it's not transfer apps howw can i fix that problem?",
"is there any way to download torrents on ios 6.1?? or iphone 4 because i tried many ways over cydia and nothing works so am asking who know for a way to download torrents over my iphone 4 ios 6.1",
"Hi is there any jailbreak app for acess block sites ,??? Help plz because itried many ways and nothing works",
"i need to know when do u make new jailbreak for ios 6.1.3 becauss and is there any oter way for 4g or 3gs ?? like redsn0w or something else?",
"i heard that jailbreak wil be able for ios 7 but the real question r u ready for it i mean for jailbreaking it or like 6.1.3 ? am waiting this awesome team to make the new jailbreak for us and i thx u for all u works on many ios .",
"hi.I JAILBREAK MY iPHONE FOR SEVERAL TIMES BEFORE IT WORKS FOR IOS 6.0.1 .1DAY AGO I WAS TRYING TO JUST BOOT MY IPHONE BUT WHEN II TRY 2 DO IT IT JUST SAY ''EXPLOIT FAILD'' WHEN THE IPHONE TRYS TO REBOOT I TRIED EVERY THING I DOWNLOADED LATEST VERSION OF ITUNES AND I ALWAYS SELECT IPSW BEFORE JUST A BOOT BUT NOTHING WORK PLZ HELP.",
"Jailbreaqa said there is jailbreak to ios 6.1.3 but tetherd and for 4th generator i found another better than reds0w and it works with me i wish it works to u too!",
"First of all u need sn0wbreeze (u can search for it on google and download it) Second u will need ios 6.1.3 firmware (u can find it on google too) Third u will need to backup ur device full backup 4th now open unrar sn0wbreeze and connect ur phone by wire to the computer. 5th there is an message will appear to u press ok and then next then click browse for ipsw (6.1.3 ios) then next then select simple mode after that it will take some mins to complete the loading then it will tells u it's done click ok and then put ur device in dfu mode by the instrdactions on the app and then it will loads. Note : run app as admin 6th now it will finish and the itunes will run automatically if not just run it and u need to use iTunes 10 at least or higher version now click on shift+restore or options+restore if u r on mac an select sn0wbreez ipsw on desktop. after that u will find new window click on restore and it will going to begin wait to finish and then go to ibooty on desktop open it and go to dfu mode and then follow the instradction and then u will find cydia ! Now u can restore .",
"I accidentally upgraded my iphone 4 to 6.1.3 and baseband to 4.12.5 (we were using a gevey sim before and created a backup on itunes before updating)",
"and its turning black from corners..its freaking me out plz help...z diz normal");
